import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
globalThis.document={createElement:()=>({relList:{supports:()=>true}})};
globalThis.PoraDemo={};
const {KeysIdeas:k,keysInitialState}=createRequire(import.meta.url)('../tmp/sections-engine.cjs');
function initial(){const s=keysInitialState();return {...s,ideas:k.initial('couple',10),navigation:{...s.navigation,screen:{type:'ideas'}}};}
test('advice engine advances cards and asks budget after three answers',()=>{let s=initial();for(let i=0;i<3;i++){const id=s.ideas.current.id;s=k.reduce(s,{type:'IDEAS_ANSWER',id,liked:true});assert.ok(s.ideas.likes.includes(id));}assert.equal(s.ideas.current.type,'ask');assert.equal(s.ideas.current.id,'budget');s=k.reduce(s,{type:'IDEAS_ASK',id:'budget',value:'6000'});assert.equal(s.ideas.answers.budget,'6000');assert.notEqual(s.ideas.current.id,'budget');});
test('changing company removes incompatible adult-only wishes',()=>{let s=initial();s=k.reduce(s,{type:'IDEAS_TOGGLE',id:'adults'});s=k.reduce(s,{type:'IDEAS_COMPANY',company:'kids'});assert.ok(!s.ideas.likes.includes('adults'));assert.ok(s.ideas.note.text.includes('Убрали'));});
test('ranking honors required amenities and separates compromises',()=>{let s=initial();s=k.reduce(s,{type:'IDEAS_WISH',likes:['hammam','pool'],answers:{}});const result=k.rank(s.ideas,s.search,0);assert.ok(result.fitting.length>0);assert.ok(result.others.length>0);assert.ok(result.fitting.every(h=>h.spa&&h.pool));assert.ok(k.reasons(result.fitting[0],s.ideas,s.search).length>=2);s=k.reduce(s,{type:'IDEAS_DROP',id:'hammam'});assert.ok(k.rank(s.ideas,s.search).fitting.length>=result.fitting.length);});
test('seasons, free-text wishes and no-match fallback remain available',()=>{assert.ok(k.locked(k.get('ski'),10));assert.equal(k.locked(k.get('ski'),1),null);assert.deepEqual(k.parse('Хочу спа, бассейн и парковку').likes,['hammam','pool','car']);let s=initial();s=k.reduce(s,{type:'IDEAS_WISH',likes:['adults','kidsclub'],answers:{budget:'6000'}});const result=k.rank(s.ideas,s.search);assert.ok(result.fitting.length+result.others.length>0);});
test('match badge counts all preferences and excludes uncertain features and budget',()=>{const s=initial();const hotel={...k.rank(s.ideas,s.search).fitting[0],spa:true,pool:true,beach:true,quiet:true,parking:true,seaDistance:50};const ideas={...s.ideas,likes:['hammam','pool','beach','sleep','car','breakfast','yoga'],answers:{budget:'8000'}};assert.deepEqual(k.matches(hotel,ideas),{matched:5,total:7});assert.deepEqual(k.matches(hotel,{...ideas,likes:[]}),{matched:0,total:0});});
