// Checkout controls share the application typography and keep card details in memory only.
const keysCheckoutMethods=[{id:'card',name:'Картой',detail:'Новая банковская карта',icon:'card'},{id:'sbp',name:'СБП',detail:'Через приложение банка',icon:'qr'},{id:'digital-ruble',name:'Цифровой рубль',detail:'Через цифровой кошелёк',icon:'coins'},{id:'sberpay',name:'SberPay',detail:'Через СберБанк Онлайн',icon:'card'},{id:'yandexpay',name:'Яндекс Пэй',detail:'Через приложение Яндекс',icon:'card'}];
function keysCardErrors(card,now=new Date()){
 const number=card.number.replace(/\D/g,''),expiry=card.expiry.replace(/\D/g,''),cvv=card.cvv.replace(/\D/g,'');
 let sum=0;for(let i=number.length-1,odd=false;i>=0;i--,odd=!odd){let digit=Number(number[i]);if(odd){digit*=2;if(digit>9)digit-=9;}sum+=digit;}
 const month=Number(expiry.slice(0,2)),year=2000+Number(expiry.slice(2));
 return {number:number.length>=16&&number.length<=19&&sum%10===0&&!/^0+$/.test(number)?'':'Проверьте номер карты',expiry:expiry.length===4&&month>=1&&month<=12&&(year>now.getFullYear()||year===now.getFullYear()&&month>=now.getMonth()+1)?'':'Проверьте срок действия',cvv:/^\d{3}$/.test(cvv)?'':'Введите 3 цифры'};
}
function keysPointsLimit(draft,balance){return Math.max(0,Math.floor(Math.min(balance,Ul(draft)*0.2)));}
function keysPointsUsed(draft){return draft.usePoints?Math.max(0,Math.floor(Math.min(draft.pointsAmount??rs.cost,Ul(draft)*0.2))):0;}
function KeysPaymentOptions(){
 const {state,dispatch}=J(),draft=state.reservation,[other,setOther]=E.useState(false),[card,setCard]=E.useState({number:'',expiry:'',cvv:''}),[touched,setTouched]=E.useState({});
 const errors=keysCardErrors(card),valid=Object.values(errors).every(value=>!value),method=draft.paymentMethod;
 E.useEffect(()=>{dispatch({type:'KEYS_CARD_READY',ready:method==='card'&&valid});},[method,valid]);
 const select=id=>dispatch({type:'RESERVATION_METHOD',method:id});
 const option=item=>n.jsxs('div',{className:'keys-pay-method-item'+(method===item.id?' is-selected':''),children:[
  n.jsxs('label',{className:'keys-pay-method',children:[n.jsx(D,{name:item.icon,className:'size-5'}),n.jsxs('span',{children:[n.jsx('strong',{children:item.name}),n.jsx('small',{children:item.detail})]}),n.jsx('input',{type:'radio',name:'keys-pay-method',value:item.id,checked:method===item.id,onChange:()=>select(item.id),'aria-label':item.name,...(item.id==='card'?{'aria-controls':'keys-new-card-fields'}:{})})]}),
  method===item.id&&item.id==='card'&&n.jsx('div',{id:'keys-new-card-fields',className:'keys-pay-card',role:'group','aria-label':'Данные карты',children:n.jsxs('div',{className:'keys-pay-card-fields',children:[field('number','Номер карты','0000 0000 0000 0000',23),field('expiry','Срок действия','ММ/ГГ',5),field('cvv','CVC / CVV','•••',3)]})}),
  method===item.id&&item.id!=='card'&&n.jsx('p',{className:'keys-pay-hint',children:method==='sbp'?'После нажатия «Оплатить» выберите банк.':method==='digital-ruble'?'Подтвердите оплату в цифровом кошельке.':'Подтвердите оплату в приложении выбранного сервиса.'})
 ]},item.id);
 const field=(id,label,placeholder,maxLength)=>n.jsxs('label',{className:'keys-pay-field'+(id==='number'?' is-wide':''),children:[n.jsx('span',{children:label}),n.jsx('input',{type:id==='cvv'?'password':'text',inputMode:'numeric',autoComplete:'off',placeholder,maxLength,value:card[id],'aria-invalid':!!(touched[id]&&errors[id]),'aria-describedby':touched[id]&&errors[id]?'keys-card-error-'+id:undefined,onBlur:()=>setTouched(old=>({...old,[id]:true})),onChange:event=>{let value=event.target.value.replace(/\D/g,'');value=id==='number'?value.slice(0,19).replace(/(.{4})/g,'$1 ').trim():id==='expiry'?value.slice(0,4).replace(/^(\d{2})(\d)/,'$1/$2'):value.slice(0,3);setCard(old=>({...old,[id]:value}));}}),touched[id]&&errors[id]&&n.jsx('small',{id:'keys-card-error-'+id,role:'alert',children:errors[id]})]});
 return n.jsxs('section',{className:'keys-checkout-panel keys-pay-section','aria-label':'Способ оплаты',children:[n.jsx('h2',{children:'Способ оплаты'}),n.jsxs('div',{className:'keys-pay-methods',children:[keysCheckoutMethods.slice(0,3).map(option),n.jsxs('button',{type:'button',className:'keys-pay-other','aria-expanded':other,onClick:()=>setOther(!other),children:[n.jsx('span',{children:!other&&['sberpay','yandexpay'].includes(method)?keysCheckoutMethods.find(item=>item.id===method).name:'Другой способ'}),n.jsx(D,{name:'chevron',className:'size-4'+(other?' is-open':'')})]}),other&&keysCheckoutMethods.slice(3).map(option)]})]});
}
function KeysPaymentPoints({draft}){
 const {state,dispatch}=J(),limit=keysPointsLimit(draft,state.loyalty.balance),amount=keysPointsUsed(draft),[input,setInput]=E.useState(String(amount||''));
 const apply=value=>dispatch({type:'RESERVATION_POINTS',enabled:true,amount:value});
 E.useEffect(()=>{if(amount>limit)apply(limit);},[amount,limit]);
 return n.jsxs('section',{className:'keys-checkout-panel keys-pay-section keys-pay-points','aria-label':'Баллы Ключей',children:[n.jsxs('div',{className:'keys-pay-points-head',children:[n.jsxs('div',{children:[n.jsx('h2',{children:'Баллы Ключей'}),n.jsx('p',{children:'На счёте '+ln(state.loyalty.balance)+' баллов'})]}),n.jsxs('label',{className:'keys-pay-use-points',children:[n.jsx('span',{children:'Списать'}),n.jsx('input',{type:'checkbox',checked:draft.usePoints,disabled:limit===0,onChange:event=>{const value=Math.min(limit,Number(input)||rs.cost);setInput(String(value));dispatch({type:'RESERVATION_POINTS',enabled:event.target.checked,amount:value});}})]})]}),draft.usePoints&&n.jsxs(n.Fragment,{children:[n.jsxs('div',{className:'keys-pay-points-entry',children:[n.jsxs('label',{className:'keys-pay-field',children:[n.jsx('span',{children:'Баллов к списанию'}),n.jsx('input',{type:'text',inputMode:'numeric',value:input,'aria-label':'Баллов к списанию',onChange:event=>{const raw=event.target.value.replace(/\D/g,'').slice(0,8);setInput(raw);apply(Number(raw));},onBlur:()=>setInput(String(keysPointsUsed(draft)))})]}),n.jsx('button',{type:'button',className:'keys-pay-max',onClick:()=>{setInput(String(limit));apply(limit);},children:'Максимум'})]}),n.jsxs('div',{className:'keys-pay-points-note','aria-live':'polite',children:[n.jsx('span',{children:'1 балл = 1 ₽ · до '+ln(limit)+' баллов'}),n.jsx('strong',{children:'−'+Te(amount*rs.discount/rs.cost)})]})]})]});
}
