// Checkout selects a payment method; card details belong to the later payment step.
const keysCheckoutMethods=[{id:'arrival',name:'При заселении',detail:'Сейчас ничего платить не нужно',icon:'hotel'},{id:'card',name:'Картой',detail:'Данные карты — на следующем шаге',icon:'card'},{id:'sbp',name:'СБП',detail:'Через приложение банка',icon:'qr'},{id:'digital-ruble',name:'Цифровой рубль',detail:'Через цифровой кошелёк',icon:'coins'},{id:'sberpay',name:'SberPay',detail:'Через СберБанк Онлайн',icon:'card'},{id:'yandexpay',name:'Яндекс Пэй',detail:'Через приложение Яндекс',icon:'card'}];
function keysPointsLimit(draft,balance){return Math.max(0,Math.floor(Math.min(balance,Ul(draft)*0.2)));}
function keysPointsUsed(draft){return draft.usePoints?Math.max(0,Math.floor(Math.min(draft.pointsAmount??rs.cost,Ul(draft)*0.2))):0;}
function keysPaymentMethodMatches(id,filter){return filter==='all'||(filter==='later'?id==='arrival':id!=='arrival');}
function KeysCancellationPolicy({draft}){
 const {state}=J(),tariff=Sr(draft.hotelId,draft.tariffId),deadline=tariff.refundable?Hx(tariff,draft.arrival):null,free=tariff.refundable&&state.tripContext.today<=deadline;
 return n.jsxs('section',{className:'keys-checkout-panel keys-cancellation-policy','aria-label':'Условия отмены',children:[n.jsx('h2',{children:'Условия отмены'}),n.jsxs('div',{className:'keys-cancellation-copy',children:[n.jsx(D,{name:'shield',className:'size-5'}),n.jsxs('div',{children:[n.jsx('h3',{children:free?'Бесплатная отмена до '+qm(deadline):tariff.refundable?'Отмена со штрафом':'Невозвратный тариф'}),n.jsx('p',{children:tariff.refundable?(free?'После этой даты штраф — стоимость ':'Срок бесплатной отмены истёк. Штраф — стоимость ')+(tariff.penaltyNights===1?'одной ночи':tariff.penaltyNights+' ночей')+'.':'При отмене взимается полная стоимость проживания.'})]})]})]});
}
function KeysPaymentOptions(){
 const {state,dispatch}=J(),draft=state.reservation,[other,setOther]=E.useState(false),[filter,setFilter]=E.useState('all');
 const method=draft.paymentMethod,visible=keysCheckoutMethods.filter(item=>keysPaymentMethodMatches(item.id,filter)),main=visible.filter(item=>!['sberpay','yandexpay'].includes(item.id)),extra=visible.filter(item=>['sberpay','yandexpay'].includes(item.id));
 const select=id=>dispatch({type:'RESERVATION_METHOD',method:id});
 const option=item=>n.jsxs('div',{className:'keys-pay-method-item'+(method===item.id?' is-selected':''),children:[
  n.jsxs('label',{className:'keys-pay-method',children:[n.jsx(D,{name:item.icon,className:'size-5'}),n.jsxs('span',{children:[n.jsx('strong',{children:item.name}),n.jsx('small',{children:item.detail})]}),n.jsx('input',{type:'radio',name:'keys-pay-method',value:item.id,checked:method===item.id,onChange:()=>select(item.id),'aria-label':item.name})]}),
  method===item.id&&item.id!=='card'&&n.jsx('p',{className:'keys-pay-hint',children:method==='arrival'?'Оплатите проживание и выбранные услуги в отеле при заселении.':method==='sbp'?'После нажатия «Оплатить» выберите банк.':method==='digital-ruble'?'Подтвердите оплату в цифровом кошельке.':'Подтвердите оплату в приложении выбранного сервиса.'})
 ]},item.id);
 return n.jsxs('section',{className:'keys-checkout-panel keys-pay-section','aria-label':'Способ оплаты',children:[n.jsx('h2',{children:'Способ оплаты'}),n.jsx('div',{className:'keys-results-filters keys-pay-method-filters',role:'group','aria-label':'Когда платить',children:[['all','Все'],['now','Предоплата сейчас'],['later','Без оплаты сейчас']].map(([id,label])=>n.jsx('button',{type:'button','aria-pressed':filter===id,onClick:()=>setFilter(id),children:label},id))}),n.jsxs('div',{className:'keys-pay-methods',children:[main.map(option),!!extra.length&&n.jsxs('button',{type:'button',className:'keys-pay-other','aria-expanded':other,onClick:()=>setOther(!other),children:[n.jsx('span',{children:!other&&['sberpay','yandexpay'].includes(method)?keysCheckoutMethods.find(item=>item.id===method).name:'Другой способ'}),n.jsx(D,{name:'chevron',className:'size-4'+(other?' is-open':'')})]}),other&&extra.map(option)]}),method&&!keysPaymentMethodMatches(method,filter)&&n.jsx('p',{className:'keys-pay-filter-selection',children:'Выбрано: '+keysCheckoutMethods.find(item=>item.id===method)?.name})]});
}
function KeysPaymentPoints({draft}){
 const {state,dispatch}=J(),limit=keysPointsLimit(draft,state.loyalty.balance),amount=keysPointsUsed(draft),[input,setInput]=E.useState(String(amount||''));
 const apply=value=>dispatch({type:'RESERVATION_POINTS',enabled:true,amount:value});
 E.useEffect(()=>{if(amount>limit)apply(limit);},[amount,limit]);
 E.useEffect(()=>{setInput(String(amount));},[amount]);
 return n.jsxs('section',{className:'keys-checkout-panel keys-pay-section keys-pay-points','aria-label':'Баллы Ключей',children:[n.jsxs('div',{className:'keys-pay-points-head',children:[n.jsxs('div',{children:[n.jsx('h2',{children:'Баллы Ключей'}),n.jsx('p',{children:'На счёте '+ln(state.loyalty.balance)+' баллов'})]}),n.jsxs('label',{className:'keys-pay-use-points',children:[n.jsx('span',{children:'Списать'}),n.jsx('input',{type:'checkbox',checked:draft.usePoints,disabled:limit===0,onChange:event=>{const value=Math.min(limit,Number(input)||rs.cost);setInput(String(value));dispatch({type:'RESERVATION_POINTS',enabled:event.target.checked,amount:value});}})]})]}),draft.usePoints&&n.jsxs(n.Fragment,{children:[n.jsxs('div',{className:'keys-pay-points-slider',children:[n.jsx('input',{type:'range',min:0,max:limit,step:1,value:Math.min(amount,limit),disabled:limit===0,'aria-label':'Количество баллов к списанию','aria-valuetext':ln(amount)+' баллов — '+Te(amount)+' скидки',style:{'--points-progress':(limit?Math.min(100,amount/limit*100):0)+'%'},onChange:event=>{const value=Number(event.target.value);setInput(String(value));apply(value);}}),n.jsxs('div',{className:'keys-pay-points-bounds','aria-hidden':true,children:[n.jsx('span',{children:'0'}),n.jsx('span',{children:ln(limit)})]})]}),n.jsxs('div',{className:'keys-pay-points-entry',children:[n.jsxs('label',{className:'keys-pay-field',children:[n.jsx('span',{children:'Баллов к списанию'}),n.jsx('input',{type:'text',inputMode:'numeric',value:input,'aria-label':'Баллов к списанию',onChange:event=>{const raw=event.target.value.replace(/\D/g,'').slice(0,8);setInput(raw);apply(Number(raw));},onBlur:()=>setInput(String(keysPointsUsed(draft)))})]}),n.jsx('button',{type:'button',className:'keys-pay-max',onClick:()=>{setInput(String(limit));apply(limit);},children:'Максимум'})]}),n.jsxs('div',{className:'keys-pay-points-note','aria-live':'polite',children:[n.jsx('span',{children:'1 балл = 1 ₽ · до '+ln(limit)+' баллов'}),n.jsx('strong',{children:'−'+Te(amount*rs.discount/rs.cost)})]})]})]});
}
